@startuml

<style>

    .project {
        BackgroundColor: DarkOrchid
        FontColor: White
    }

    .doing {
        BackgroundColor: Green
        FontColor: white
    }

</style>

card edge_enums <<project>> {
    card create_paths <<doing>>
    card remove_paths
    card save_paths_to_firebase
    card get_paths_from_firebase
}

@enduml