@startmindmap

* paths
** clicking anywhere but on the next point with stop path
** clicking on same point will stop path
** clicking in menues will stop path
*** Will need to bring click history state up`

@endmindmap