@startmindmap

<style>
MindmapDiagram {

  .bug {
    BackgroundColor: Crimson
    FontColor: White
  }

  .question {
    BackgroundColor: PowderBlue
  }

  .ready {
    BackgroundColor: YellowGreen
    FontColor: Black
  }

  .report {
    BackgroundColor: SlateGrey
    FontColor: White
  }

  .backlog * {
    BackgroundColor: Ivory
    FontColor: Grey
    LineColor: Lavender
  }

  .hold * {
    BackgroundColor: GoldenRod
    FontColor: Black
  }

  .priority {
    BackgroundColor: MediumVioletRed
    FontColor: White
  }

  .info * {
    BackgroundColor: LemonChiffon
  }
}
</style>

* zoom not preserving map on reload <<bug>>
** Bring Hex matrix up so it's not reset whenever we change the scale?

* paths
** Stopping path chain
*** clicking anywhere but on the next point with stop path
*** clicking on same point will stop path

* icons
** size a pre-built svg
** New icons to support
*** city sizes
*** flora and fauna
*** site
*** fortification
*** waterfall
*** cave
*** peak

* text
** hidden text
*** icon when there is hidden text
** editor full page view
** visible text on page
** pick text size
** delete text
** support links to google doc bookmark
*** text link
*** bookmark location
*** more than one link?

* hexagon links (to support putting notes in another tool)
* Menu link to take to top of google doc

* Cleanup
** Move hex path clearing logic into the hexagon class
** simplify nesting in the hex_grid on_click function

@endmindmap