@startmindmap

<style>

MindmapDiagram {
  node {
    MaximumWidth: 200
  }

  .bug {
    BackgroundColor: Crimson
    FontColor: White
  }
}

</style>

* paths
** Stopping path chain
*** not stopping after switching path type <<bug>>
*** clicking anywhere but on the next point with stop path
*** clicking on same point will stop path
*** clicking in menues will stop path
** First click not starting path <<bug>>

* icons
** size a pre-built svg
** New icons to support
*** city sizes
*** flora and fauna
*** site
*** fortification
*** waterfall
*** cave
*** peak

* text
** hidden text
*** icon when there is hidden text
** editor full page view
** visible text on page
** pick text size
** delete text
** support links to google doc bookmark
*** text link
*** bookmark location
*** more than one link?

* hexagon links (to support putting notes in another tool)
* Menu link to take to top of google doc

@endmindmap