  const categoryMapping = {
            'Settlement': ['Village', 'Town', 'City', 'Hamlet', 'Fort', 'Keep', 'Castle', 'Metropolis', 'Capital', 'Port', 'Mining Town', 'Market Town', 'Trading Post', 'Farmstead', 'Ranch', 'Fishing Village', 'Frontier Outpost', 'Abbey', 'Monastery', 'Temple Complex', 'Bardic College', 'Wizard Tower', 'Necromancer Crypt', 'Thieves\' Guild Hideout', 'Goblin Camp', 'Orc Camp', 'Barbarian Yurt Camp', 'Nomad Camp', 'Nomad Caravan', 'Logging Camps', 'Lumber Camp', 'Gem Mines', 'Crystal Mines', 'Open-pit Quarries', 'Sawmills', 'Shipyard', 'Plantation', 'Mill', 'Watchtower', 'Lighthouse', 'Pier', 'Dock', 'Alchemist Laboratory', 'Druid Circle', 'Shepherd Huts', 'Mine Headframes', 'Stockade'],
            
            'Infrastructure': ['Bridge', 'Road', 'Aqueduct', 'Canal', 'Ferry', 'Waystone', 'Beacon', 'Milestone', 'Border', 'Tunnel', 'Lock', 'Station', 'Port', 'Harbor', 'Rail Line', 'Dragon Rail', 'Clockwork Lift', 'Mage\'s Lift', 'Teleportation Circle', 'Imperial Canal', 'Great Road', 'Royal Highway', 'Major Paved Road', 'Minor Road', 'Cart Track', 'Animal Trail', 'Mountain Pass', 'Ford', 'Stone Bridge', 'Wooden Bridge', 'Rope Bridge', 'Suspension Bridge', 'Viaduct', 'Stone Causeway', 'Causeway', 'Airship Path', 'Ferry Route', 'Scheduled Sea Lanes', 'Irrigation Ditch', 'Beacon Tower', 'Quarry Symbols', 'Floating Log Booms', 'Siding', 'Tunnel Portal', 'Mile Post', 'Provincial Boundary', 'National Boundary', 'Tribal Boundary'],
            
            'Natural': ['Forest', 'Mountain', 'River', 'Lake', 'Cave', 'Swamp', 'Desert', 'Plain', 'Valley', 'Hill', 'Cliff', 'Beach', 'Island', 'Peninsula', 'Volcano', 'Canyon', 'Plateau', 'Mesa', 'Butte', 'Ridge', 'Ravine', 'Grotto', 'Oasis', 'Marsh', 'Fen', 'Bog', 'Prairie', 'Savanna', 'Tundra', 'Glacier', 'Ice Canyon', 'Crater', 'Caldera', 'Hot Spring', 'Geyser', 'Waterfall', 'Rapids', 'Delta', 'Estuary', 'Fjord', 'Archipelago', 'Atoll', 'Reef', 'Coral', 'Dune', 'Salt Flat', 'Badlands', 'Cavern', 'Underground River', 'Underground Lake', 'Crystal Cave', 'Lava Field', 'Obsidian Plain', 'Mud Volcano', 'Lightning Field', 'Rainforest', 'Jungle', 'Mangrove Swamp', 'Dry Brushland', 'Woodland', 'Cave Entrances', 'Cave Complexes', 'Giant Trees', 'Cliff Lines', 'Coastal Bluffs', 'Mangrove Inlet', 'Bay', 'Cove', 'Strait', 'Crater Lake', 'Floating Island', 'Petrified Forests', 'Meteor Impact Craters', 'Glassed Deserts', 'Underground River Mouths', 'Rift Valley', 'Wastelands'],
            
            'Magical': ['Ley Line Convergence', 'Mana Well', 'Portal Nexus', 'Elemental Nexus', 'Fey Glade', 'Shadow Realm', 'Astral Gate', 'Planar Gate', 'Time Rift', 'Dimensional Portal', 'Magic Circle', 'Arcane Storm', 'Wild Magic Zone', 'Dead Magic Zone', 'Antimagic Field', 'Floating Island', 'Crystal Field', 'Singing Stones', 'Dreaming Pool', 'Spirit Grove', 'Ghost Town', 'Haunted Ruins', 'Cursed Battlefield', 'Living Garden', 'Evernight Forest', 'Moonlit Clearing', 'Starfall Crater', 'Fire Plane Rift', 'Ice Plane Rift', 'Fairy Circle', 'Mana Springs', 'Good Magic Points', 'Bad Magic Points', 'Elemental Nodes', 'Standing Portals', 'Dimensional Rifts', 'Floating Water Globes', 'History Overlay Areas', 'Time-dilated Regions', 'Creeping Corruption Hexes', 'Undead-infested Barrows', 'Legendary Beast Lairs', 'Dragon Lair', 'Roaring Flame Vents', 'Storm Eyes', 'Faerie Rings', 'Hydra Lairs', 'Kraken Lairs', 'Mist of Darkness', 'World Trees', 'Unstable Rift', 'Temporal Vortex'],
            
            'Dungeon': ['Dungeon', 'Crypt', 'Tomb', 'Catacomb', 'Labyrinth', 'Maze', 'Prison', 'Torture Chamber', 'Treasury', 'Armory', 'Barracks', 'Throne Room', 'Library', 'Laboratory', 'Workshop', 'Forge', 'Temple', 'Shrine', 'Altar', 'Ritual Chamber', 'Summoning Circle', 'Portal Room', 'Mirror Maze', 'Trap Hall', 'Puzzle Room', 'Boss Chamber', 'Treasure Vault', 'Secret Passage', 'Hidden Room', 'Escape Tunnel', 'Sewer', 'Aqueduct', 'Mine', 'Quarry', 'Underdark', 'Spider Nest', 'Goblin Warrens', 'Orc Stronghold', 'Dragon Hoard', 'Lich\'s Sanctum', 'Demon Portal', 'Bandit Hideout', 'Smuggler Tunnel', 'Ancient Palace', 'Lost Library', 'Forgotten Vault', 'Alchemist Workshop', 'Arcane Laboratory', 'Elemental Forge', 'Clockwork Maze', 'Shadow Keep', 'Sunken City', 'Sunken Temple', 'Underdark Cavern', 'Underground Forge', 'Giant Hive', 'Ooze Pits', 'Monster Lair', 'Dwarven Mine', 'Mothballed Armory', 'Timeline Rupture'],
            
            'Ruin': ['Ruined Castle', 'Abandoned Temple', 'Lost City', 'Ancient Tower', 'Forgotten Tomb', 'Collapsed Mine', 'Destroyed Village', 'Sunken Ship', 'Crashed Airship', 'Battlefield', 'Graveyard', 'Memorial', 'Monument', 'Statue', 'Obelisk', 'Stone Circle', 'Pyramid', 'Ziggurat', 'Colosseum', 'Amphitheater', 'Forum', 'Bath House', 'Villa', 'Palace', 'Fortress', 'Wall', 'Gate', 'Bridge', 'Road', 'Aqueduct', 'Harbor', 'Lighthouse', 'Observatory', 'Library', 'Museum', 'Temple', 'Shrine', 'Altar', 'Tomb', 'Mausoleum', 'Necropolis', 'Ossuary', 'Charnel House', 'Abandoned Fortress', 'Abandoned Mine', 'Ancient Observatory', 'Ancient Palace', 'Buried Ziggurat', 'Collapsed Temple', 'Cracked Pyramid', 'Crumbling Aqueduct', 'Cursed Ruins', 'Deserted Battlefield', 'Fallen Monolith', 'Flooded Courtyard', 'Forgotten Citadel', 'Haunted Manor', 'Overgrown Villa', 'Ruined Castle', 'Shattered Coliseum', 'Shattered Obelisk', 'Sundered Wall', 'Sunken Ruins', 'Toppled Statue', 'Broken Bridge'],
            
            'Sacred Site': ['Temple', 'Shrine', 'Altar', 'Sacred Grove', 'Holy Spring', 'Pilgrimage Site', 'Oracle', 'Monastery', 'Abbey', 'Cathedral', 'Chapel', 'Sanctuary', 'Sacred Mountain', 'Sacred Lake', 'Sacred Cave', 'Stone Circle', 'Standing Stones', 'Burial Mound', 'Necropolis', 'Cemetery', 'Crypt', 'Tomb', 'Mausoleum', 'Ossuary', 'Charnel House', 'Ritual Site', 'Sacrificial Altar', 'Summoning Circle', 'Portal', 'Gateway', 'Nexus', 'Convergence', 'Crossing', 'Threshold', 'Boundary', 'Veil', 'Sanctified Chapel', 'High Altar', 'Divine Reliquary', 'Sacred Grove', 'Holy Spring', 'Blessed Meadow', 'Consecrated Fountain', 'Hallowed Crypt', 'Saint\'s Tomb', 'Healing Shrine', 'Oracle Cave', 'Oracle Sites', 'Sacred Mountain', 'Spirit Tree', 'Angelic Gate', 'Celestial Amphitheater', 'Dream-shrines', 'Pilgrimage Route', 'Sacred Pool'],
            
            'Planar': ['Astral Gate', 'Ethereal Crossing', 'Shadowfell Portal', 'Feywild Crossing', 'Elemental Vortex', 'Infernal Gate', 'Celestial Bridge', 'Chaos Rift', 'Order Nexus', 'Dream Gateway', 'Nightmare Passage', 'Death\'s Door', 'Life Spring', 'Time Portal', 'Space Rift', 'Dimensional Tear', 'Planar Convergence', 'Cosmic Alignment', 'Stellar Gateway', 'Void Portal', 'Abyss Entrance', 'Heaven\'s Gate', 'Hell\'s Mouth', 'Purgatory Path', 'Limbo Link', 'Pandemonium Portal', 'Mechanus Gate', 'Arborea Access', 'Bytopia Bridge', 'Elysium Entry', 'Beastlands Boundary', 'Arcadia Arch', 'Ysgard Yawning', 'Acheron Aperture', 'Gehenna Gateway', 'Carceri Crack', 'Hades Hole', 'Dreamscape Gateway', 'Heavenly Stair'],
            
            'Underwater': ['Coral Reef', 'Kelp Forest', 'Underwater Cave', 'Shipwreck', 'Sunken City', 'Underwater Volcano', 'Trench', 'Seamount', 'Underwater Ridge', 'Brine Pool', 'Hydrothermal Vent', 'Underwater Canyon', 'Abyssal Plain', 'Continental Shelf', 'Underwater Mountain', 'Underwater Valley', 'Underwater Desert', 'Underwater Forest', 'Underwater Meadow', 'Underwater Ruins', 'Underwater Temple', 'Underwater Palace', 'Underwater Fortress', 'Underwater Mine', 'Underwater Laboratory', 'Underwater Observatory', 'Underwater Farm', 'Underwater Garden', 'Merfolk City', 'Sahuagin Lair', 'Kraken Domain', 'Dragon Turtle Territory', 'Aboleth Realm', 'Elemental Water Node', 'Portal to Water Plane', 'Underwater Rift', 'Underwater Nexus', 'Pearl Reef', 'Sea Cave', 'Coral Palace', 'Kelp Forest', 'Derelict Hulks', 'Blue Hole', 'Merfolk Palaces', 'Coral Cities', 'Amphibia Towns', 'Siren Shoals', 'Oyster Beds', 'Sea-grass Meadows', 'Ridge', 'Rift Valley', 'Abyssal Plain', 'Lava Tongues', 'Vent Field', 'Vent Plumes', 'Underwater Volcano Cones', 'Rogue Wave Zones', 'Whirlpool Icons', 'Sunken Treasure Fleets', 'Ship Graveyard', 'Submerged Mountain', 'Merfolk City', 'Sahuagin Lair', 'Triton Fortress', 'Sunken Shipwreck']
        };

    